version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: emsdb
      POSTGRES_USER: emsuser
      POSTGRES_PASSWORD: 00000000
    ports:
      - "5436:5432"
    networks:
      - ems-network

  taskservice:
    build: ./
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/emsdb
      SPRING_DATASOURCE_USERNAME: emsuser
      SPRING_DATASOURCE_PASSWORD: 00000000
      USER_URL: http://userservice:8080/api/v1
    ports:
      - "8081:8080"
    networks:
      - ems-network
networks:
  ems-network:
    external: true